// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"BRSBackend/pkg/models"
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// BookRentStats defines model for BookRentStats.
type BookRentStats struct {
	BookTitle   *string `json:"book_title,omitempty"`
	RentedCount *int    `json:"rented_count,omitempty"`
}

// Books defines model for Books.
type Books = models.Book

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest = models.Librarian

// OverdueUser defines model for OverdueUser.
type OverdueUser struct {
	DateRented  *time.Time `json:"date_rented,omitempty"`
	DaysOverdue *int       `json:"days_overdue,omitempty"`
	Phone       *string    `json:"phone,omitempty"`
	StudentName *string    `json:"student_name,omitempty"`
	TotalBooks  *int       `json:"total_books,omitempty"`
}

// PaginationInfo defines model for PaginationInfo.
type PaginationInfo struct {
	// HasNext Whether there are more items available
	HasNext *bool `json:"has_next,omitempty"`

	// HasPrevious Whether there are previous items available
	HasPrevious *bool `json:"has_previous,omitempty"`

	// Limit Maximum number of items returned
	Limit *int `json:"limit,omitempty"`

	// Offset Number of items skipped
	Offset *int `json:"offset,omitempty"`

	// Total Total number of items available
	Total *int `json:"total,omitempty"`
}

// RentReport defines model for RentReport.
type RentReport struct {
	TopBooks      *[]BookRentStats `json:"top_books,omitempty"`
	TotalRents    *int             `json:"total_rents,omitempty"`
	TotalStudents *int             `json:"total_students,omitempty"`
}

// RentRequest defines model for RentRequest.
type RentRequest struct {
	BookIds   []openapi_types.UUID `json:"book_ids"`
	StudentId openapi_types.UUID   `json:"student_id"`
}

// RentSummary defines model for RentSummary.
type RentSummary struct {
	BookTitle   *string             `json:"book_title,omitempty"`
	CartId      *openapi_types.UUID `json:"cart_id,omitempty"`
	RentId      *openapi_types.UUID `json:"rent_id,omitempty"`
	RentedDate  *time.Time          `json:"rented_date,omitempty"`
	StudentName *string             `json:"student_name,omitempty"`
}

// Students defines model for Students.
type Students = models.Student

// LimitParam defines model for limitParam.
type LimitParam = int32

// OffsetParam defines model for offsetParam.
type OffsetParam = int32

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// InvalidRequestBody defines model for InvalidRequestBody.
type InvalidRequestBody = Error

// InvalidRequestParameters defines model for InvalidRequestParameters.
type InvalidRequestParameters = Error

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// ListOrSearchBooksParams defines parameters for ListOrSearchBooks.
type ListOrSearchBooksParams struct {
	// Query Optional search term (partial title match or exact ID match)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Limit Maximum number of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before returning the results.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListOverdueRentalsParams defines parameters for ListOverdueRentals.
type ListOverdueRentalsParams struct {
	StudentCardId *string `form:"student_card_id,omitempty" json:"student_card_id,omitempty"`

	// Limit Maximum number of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before returning the results.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRentsParams defines parameters for ListRents.
type ListRentsParams struct {
	// BookName Filter by book title (partial match)
	BookName *string `form:"book_name,omitempty" json:"book_name,omitempty"`

	// StudentName Filter by student first or last name (partial match)
	StudentName *string `form:"student_name,omitempty" json:"student_name,omitempty"`

	// Date Filter by rent date (YYYY-MM-DD)
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`

	// Limit Maximum number of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before returning the results.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetRentalReportsParams defines parameters for GetRentalReports.
type GetRentalReportsParams struct {
	// Limit Maximum number of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before returning the results.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetRentedBooksByStudentParams defines parameters for GetRentedBooksByStudent.
type GetRentedBooksByStudentParams struct {
	// StudentCardId Student card id
	StudentCardId *string `form:"student_card_id,omitempty" json:"student_card_id,omitempty"`
}

// ReturnBooksJSONBody defines parameters for ReturnBooks.
type ReturnBooksJSONBody struct {
	CartId openapi_types.UUID `json:"cart_id"`
}

// ListAllStudentsParams defines parameters for ListAllStudents.
type ListAllStudentsParams struct {
	// Limit Maximum number of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before returning the results.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// AddBookJSONRequestBody defines body for AddBook for application/json ContentType.
type AddBookJSONRequestBody = Books

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateRentTransactionJSONRequestBody defines body for CreateRentTransaction for application/json ContentType.
type CreateRentTransactionJSONRequestBody = RentRequest

// ReturnBooksJSONRequestBody defines body for ReturnBooks for application/json ContentType.
type ReturnBooksJSONRequestBody ReturnBooksJSONBody

// AddStudentJSONRequestBody defines body for AddStudent for application/json ContentType.
type AddStudentJSONRequestBody = Students

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List or search books (order by newly created books)
	// (GET /books)
	ListOrSearchBooks(w http.ResponseWriter, r *http.Request, params ListOrSearchBooksParams)
	// Add a new book
	// (POST /books)
	AddBook(w http.ResponseWriter, r *http.Request)
	// librarian login
	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout librarian
	// (POST /logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get overdue rentals
	// (GET /overdues)
	ListOverdueRentals(w http.ResponseWriter, r *http.Request, params ListOverdueRentalsParams)
	// Get list of all rents with optional filters
	// (GET /rents)
	ListRents(w http.ResponseWriter, r *http.Request, params ListRentsParams)
	// Create rental transaction
	// (POST /rents)
	CreateRentTransaction(w http.ResponseWriter, r *http.Request)
	// Get rental report
	// (GET /reports)
	GetRentalReports(w http.ResponseWriter, r *http.Request, params GetRentalReportsParams)
	// List books currently rented by a student
	// (GET /returns)
	GetRentedBooksByStudent(w http.ResponseWriter, r *http.Request, params GetRentedBooksByStudentParams)
	// Mark a cart as returned
	// (PUT /returns)
	ReturnBooks(w http.ResponseWriter, r *http.Request)
	// List all students
	// (GET /students)
	ListAllStudents(w http.ResponseWriter, r *http.Request, params ListAllStudentsParams)
	// Register a new student
	// (POST /students)
	AddStudent(w http.ResponseWriter, r *http.Request)
	// Get a Student by ID
	// (GET /students/{id})
	GetStudentById(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List or search books (order by newly created books)
// (GET /books)
func (_ Unimplemented) ListOrSearchBooks(w http.ResponseWriter, r *http.Request, params ListOrSearchBooksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new book
// (POST /books)
func (_ Unimplemented) AddBook(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// librarian login
// (POST /login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout librarian
// (POST /logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get overdue rentals
// (GET /overdues)
func (_ Unimplemented) ListOverdueRentals(w http.ResponseWriter, r *http.Request, params ListOverdueRentalsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get list of all rents with optional filters
// (GET /rents)
func (_ Unimplemented) ListRents(w http.ResponseWriter, r *http.Request, params ListRentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create rental transaction
// (POST /rents)
func (_ Unimplemented) CreateRentTransaction(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get rental report
// (GET /reports)
func (_ Unimplemented) GetRentalReports(w http.ResponseWriter, r *http.Request, params GetRentalReportsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List books currently rented by a student
// (GET /returns)
func (_ Unimplemented) GetRentedBooksByStudent(w http.ResponseWriter, r *http.Request, params GetRentedBooksByStudentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mark a cart as returned
// (PUT /returns)
func (_ Unimplemented) ReturnBooks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all students
// (GET /students)
func (_ Unimplemented) ListAllStudents(w http.ResponseWriter, r *http.Request, params ListAllStudentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new student
// (POST /students)
func (_ Unimplemented) AddStudent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a Student by ID
// (GET /students/{id})
func (_ Unimplemented) GetStudentById(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOrSearchBooks operation middleware
func (siw *ServerInterfaceWrapper) ListOrSearchBooks(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrSearchBooksParams

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrSearchBooks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddBook operation middleware
func (siw *ServerInterfaceWrapper) AddBook(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOverdueRentals operation middleware
func (siw *ServerInterfaceWrapper) ListOverdueRentals(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOverdueRentalsParams

	// ------------- Optional query parameter "student_card_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "student_card_id", r.URL.Query(), &params.StudentCardId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "student_card_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOverdueRentals(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRents operation middleware
func (siw *ServerInterfaceWrapper) ListRents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRentsParams

	// ------------- Optional query parameter "book_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "book_name", r.URL.Query(), &params.BookName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "book_name", Err: err})
		return
	}

	// ------------- Optional query parameter "student_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "student_name", r.URL.Query(), &params.StudentName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "student_name", Err: err})
		return
	}

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameter("form", true, false, "date", r.URL.Query(), &params.Date)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRentTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateRentTransaction(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRentTransaction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRentalReports operation middleware
func (siw *ServerInterfaceWrapper) GetRentalReports(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRentalReportsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRentalReports(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRentedBooksByStudent operation middleware
func (siw *ServerInterfaceWrapper) GetRentedBooksByStudent(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRentedBooksByStudentParams

	// ------------- Optional query parameter "student_card_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "student_card_id", r.URL.Query(), &params.StudentCardId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "student_card_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRentedBooksByStudent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReturnBooks operation middleware
func (siw *ServerInterfaceWrapper) ReturnBooks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReturnBooks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAllStudents operation middleware
func (siw *ServerInterfaceWrapper) ListAllStudents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAllStudentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAllStudents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddStudent operation middleware
func (siw *ServerInterfaceWrapper) AddStudent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddStudent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStudentById operation middleware
func (siw *ServerInterfaceWrapper) GetStudentById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStudentById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/books", wrapper.ListOrSearchBooks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/books", wrapper.AddBook)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/overdues", wrapper.ListOverdueRentals)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rents", wrapper.ListRents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rents", wrapper.CreateRentTransaction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reports", wrapper.GetRentalReports)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/returns", wrapper.GetRentedBooksByStudent)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/returns", wrapper.ReturnBooks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/students", wrapper.ListAllStudents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/students", wrapper.AddStudent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/students/{id}", wrapper.GetStudentById)
	})

	return r
}

type InternalServerErrorJSONResponse Error

type InvalidRequestBodyJSONResponse Error

type InvalidRequestParametersJSONResponse Error

type UnauthorizedErrorJSONResponse Error

type ListOrSearchBooksRequestObject struct {
	Params ListOrSearchBooksParams
}

type ListOrSearchBooksResponseObject interface {
	VisitListOrSearchBooksResponse(w http.ResponseWriter) error
}

type ListOrSearchBooks200JSONResponse struct {
	Pagination *PaginationInfo `json:"pagination,omitempty"`
	Results    *[]Books        `json:"results,omitempty"`
}

func (response ListOrSearchBooks200JSONResponse) VisitListOrSearchBooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListOrSearchBooks400JSONResponse struct {
	InvalidRequestParametersJSONResponse
}

func (response ListOrSearchBooks400JSONResponse) VisitListOrSearchBooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListOrSearchBooks401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response ListOrSearchBooks401JSONResponse) VisitListOrSearchBooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListOrSearchBooks500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListOrSearchBooks500JSONResponse) VisitListOrSearchBooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddBookRequestObject struct {
	Body *AddBookJSONRequestBody
}

type AddBookResponseObject interface {
	VisitAddBookResponse(w http.ResponseWriter) error
}

type AddBook201ResponseHeaders struct {
	Location string
}

type AddBook201JSONResponse struct {
	Body struct {
		Message *string `json:"message,omitempty"`
	}
	Headers AddBook201ResponseHeaders
}

func (response AddBook201JSONResponse) VisitAddBookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type AddBook400JSONResponse struct{ InvalidRequestBodyJSONResponse }

func (response AddBook400JSONResponse) VisitAddBookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddBook401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response AddBook401JSONResponse) VisitAddBookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AddBook500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AddBook500JSONResponse) VisitAddBookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body struct {
		LibrarianId *openapi_types.UUID `json:"librarian_id,omitempty"`
		Message     *string             `json:"message,omitempty"`
	}
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Logout500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListOverdueRentalsRequestObject struct {
	Params ListOverdueRentalsParams
}

type ListOverdueRentalsResponseObject interface {
	VisitListOverdueRentalsResponse(w http.ResponseWriter) error
}

type ListOverdueRentals200JSONResponse struct {
	Pagination *PaginationInfo `json:"pagination,omitempty"`
	Results    *[]OverdueUser  `json:"results,omitempty"`
}

func (response ListOverdueRentals200JSONResponse) VisitListOverdueRentalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListOverdueRentals400JSONResponse struct {
	InvalidRequestParametersJSONResponse
}

func (response ListOverdueRentals400JSONResponse) VisitListOverdueRentalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListOverdueRentals401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response ListOverdueRentals401JSONResponse) VisitListOverdueRentalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListOverdueRentals500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListOverdueRentals500JSONResponse) VisitListOverdueRentalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListRentsRequestObject struct {
	Params ListRentsParams
}

type ListRentsResponseObject interface {
	VisitListRentsResponse(w http.ResponseWriter) error
}

type ListRents200JSONResponse struct {
	Pagination *PaginationInfo `json:"pagination,omitempty"`
	Results    *[]RentSummary  `json:"results,omitempty"`
}

func (response ListRents200JSONResponse) VisitListRentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRents400JSONResponse struct {
	InvalidRequestParametersJSONResponse
}

func (response ListRents400JSONResponse) VisitListRentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListRents401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response ListRents401JSONResponse) VisitListRentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListRents500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListRents500JSONResponse) VisitListRentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateRentTransactionRequestObject struct {
	Body *CreateRentTransactionJSONRequestBody
}

type CreateRentTransactionResponseObject interface {
	VisitCreateRentTransactionResponse(w http.ResponseWriter) error
}

type CreateRentTransaction201JSONResponse struct {
	CartId  *openapi_types.UUID `json:"cart_id,omitempty"`
	Message *string             `json:"message,omitempty"`
}

func (response CreateRentTransaction201JSONResponse) VisitCreateRentTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateRentTransaction400JSONResponse struct{ InvalidRequestBodyJSONResponse }

func (response CreateRentTransaction400JSONResponse) VisitCreateRentTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateRentTransaction401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response CreateRentTransaction401JSONResponse) VisitCreateRentTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateRentTransaction500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateRentTransaction500JSONResponse) VisitCreateRentTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRentalReportsRequestObject struct {
	Params GetRentalReportsParams
}

type GetRentalReportsResponseObject interface {
	VisitGetRentalReportsResponse(w http.ResponseWriter) error
}

type GetRentalReports200JSONResponse RentReport

func (response GetRentalReports200JSONResponse) VisitGetRentalReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRentalReports400JSONResponse struct {
	InvalidRequestParametersJSONResponse
}

func (response GetRentalReports400JSONResponse) VisitGetRentalReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetRentalReports401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response GetRentalReports401JSONResponse) VisitGetRentalReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRentalReports500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetRentalReports500JSONResponse) VisitGetRentalReportsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRentedBooksByStudentRequestObject struct {
	Params GetRentedBooksByStudentParams
}

type GetRentedBooksByStudentResponseObject interface {
	VisitGetRentedBooksByStudentResponse(w http.ResponseWriter) error
}

type GetRentedBooksByStudent200JSONResponse struct {
	Pagination *PaginationInfo `json:"pagination,omitempty"`
	Results    *[]RentSummary  `json:"results,omitempty"`
}

func (response GetRentedBooksByStudent200JSONResponse) VisitGetRentedBooksByStudentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRentedBooksByStudent400JSONResponse struct {
	InvalidRequestParametersJSONResponse
}

func (response GetRentedBooksByStudent400JSONResponse) VisitGetRentedBooksByStudentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetRentedBooksByStudent401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response GetRentedBooksByStudent401JSONResponse) VisitGetRentedBooksByStudentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRentedBooksByStudent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetRentedBooksByStudent500JSONResponse) VisitGetRentedBooksByStudentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ReturnBooksRequestObject struct {
	Body *ReturnBooksJSONRequestBody
}

type ReturnBooksResponseObject interface {
	VisitReturnBooksResponse(w http.ResponseWriter) error
}

type ReturnBooks200JSONResponse struct {
	CartId  *openapi_types.UUID `json:"cart_id,omitempty"`
	Message *string             `json:"message,omitempty"`
}

func (response ReturnBooks200JSONResponse) VisitReturnBooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ReturnBooks400JSONResponse struct{ InvalidRequestBodyJSONResponse }

func (response ReturnBooks400JSONResponse) VisitReturnBooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ReturnBooks401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response ReturnBooks401JSONResponse) VisitReturnBooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ReturnBooks500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ReturnBooks500JSONResponse) VisitReturnBooksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListAllStudentsRequestObject struct {
	Params ListAllStudentsParams
}

type ListAllStudentsResponseObject interface {
	VisitListAllStudentsResponse(w http.ResponseWriter) error
}

type ListAllStudents200JSONResponse struct {
	Pagination *PaginationInfo `json:"pagination,omitempty"`
	Results    *[]Students     `json:"results,omitempty"`
}

func (response ListAllStudents200JSONResponse) VisitListAllStudentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAllStudents400JSONResponse struct {
	InvalidRequestParametersJSONResponse
}

func (response ListAllStudents400JSONResponse) VisitListAllStudentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListAllStudents401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response ListAllStudents401JSONResponse) VisitListAllStudentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListAllStudents500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListAllStudents500JSONResponse) VisitListAllStudentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddStudentRequestObject struct {
	Body *AddStudentJSONRequestBody
}

type AddStudentResponseObject interface {
	VisitAddStudentResponse(w http.ResponseWriter) error
}

type AddStudent201ResponseHeaders struct {
	Location string
}

type AddStudent201JSONResponse struct {
	Body struct {
		Message *string `json:"message,omitempty"`
	}
	Headers AddStudent201ResponseHeaders
}

func (response AddStudent201JSONResponse) VisitAddStudentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type AddStudent400JSONResponse struct{ InvalidRequestBodyJSONResponse }

func (response AddStudent400JSONResponse) VisitAddStudentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddStudent401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response AddStudent401JSONResponse) VisitAddStudentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AddStudent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AddStudent500JSONResponse) VisitAddStudentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetStudentByIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetStudentByIdResponseObject interface {
	VisitGetStudentByIdResponse(w http.ResponseWriter) error
}

type GetStudentById200JSONResponse Students

func (response GetStudentById200JSONResponse) VisitGetStudentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetStudentById401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response GetStudentById401JSONResponse) VisitGetStudentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetStudentById404JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response GetStudentById404JSONResponse) VisitGetStudentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetStudentById500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetStudentById500JSONResponse) VisitGetStudentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List or search books (order by newly created books)
	// (GET /books)
	ListOrSearchBooks(ctx context.Context, request ListOrSearchBooksRequestObject) (ListOrSearchBooksResponseObject, error)
	// Add a new book
	// (POST /books)
	AddBook(ctx context.Context, request AddBookRequestObject) (AddBookResponseObject, error)
	// librarian login
	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout librarian
	// (POST /logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get overdue rentals
	// (GET /overdues)
	ListOverdueRentals(ctx context.Context, request ListOverdueRentalsRequestObject) (ListOverdueRentalsResponseObject, error)
	// Get list of all rents with optional filters
	// (GET /rents)
	ListRents(ctx context.Context, request ListRentsRequestObject) (ListRentsResponseObject, error)
	// Create rental transaction
	// (POST /rents)
	CreateRentTransaction(ctx context.Context, request CreateRentTransactionRequestObject) (CreateRentTransactionResponseObject, error)
	// Get rental report
	// (GET /reports)
	GetRentalReports(ctx context.Context, request GetRentalReportsRequestObject) (GetRentalReportsResponseObject, error)
	// List books currently rented by a student
	// (GET /returns)
	GetRentedBooksByStudent(ctx context.Context, request GetRentedBooksByStudentRequestObject) (GetRentedBooksByStudentResponseObject, error)
	// Mark a cart as returned
	// (PUT /returns)
	ReturnBooks(ctx context.Context, request ReturnBooksRequestObject) (ReturnBooksResponseObject, error)
	// List all students
	// (GET /students)
	ListAllStudents(ctx context.Context, request ListAllStudentsRequestObject) (ListAllStudentsResponseObject, error)
	// Register a new student
	// (POST /students)
	AddStudent(ctx context.Context, request AddStudentRequestObject) (AddStudentResponseObject, error)
	// Get a Student by ID
	// (GET /students/{id})
	GetStudentById(ctx context.Context, request GetStudentByIdRequestObject) (GetStudentByIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListOrSearchBooks operation middleware
func (sh *strictHandler) ListOrSearchBooks(w http.ResponseWriter, r *http.Request, params ListOrSearchBooksParams) {
	var request ListOrSearchBooksRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrSearchBooks(ctx, request.(ListOrSearchBooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrSearchBooks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrSearchBooksResponseObject); ok {
		if err := validResponse.VisitListOrSearchBooksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddBook operation middleware
func (sh *strictHandler) AddBook(w http.ResponseWriter, r *http.Request) {
	var request AddBookRequestObject

	var body AddBookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddBook(ctx, request.(AddBookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddBook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddBookResponseObject); ok {
		if err := validResponse.VisitAddBookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOverdueRentals operation middleware
func (sh *strictHandler) ListOverdueRentals(w http.ResponseWriter, r *http.Request, params ListOverdueRentalsParams) {
	var request ListOverdueRentalsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOverdueRentals(ctx, request.(ListOverdueRentalsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOverdueRentals")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOverdueRentalsResponseObject); ok {
		if err := validResponse.VisitListOverdueRentalsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRents operation middleware
func (sh *strictHandler) ListRents(w http.ResponseWriter, r *http.Request, params ListRentsParams) {
	var request ListRentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRents(ctx, request.(ListRentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRentsResponseObject); ok {
		if err := validResponse.VisitListRentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRentTransaction operation middleware
func (sh *strictHandler) CreateRentTransaction(w http.ResponseWriter, r *http.Request) {
	var request CreateRentTransactionRequestObject

	var body CreateRentTransactionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRentTransaction(ctx, request.(CreateRentTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRentTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRentTransactionResponseObject); ok {
		if err := validResponse.VisitCreateRentTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRentalReports operation middleware
func (sh *strictHandler) GetRentalReports(w http.ResponseWriter, r *http.Request, params GetRentalReportsParams) {
	var request GetRentalReportsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRentalReports(ctx, request.(GetRentalReportsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRentalReports")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRentalReportsResponseObject); ok {
		if err := validResponse.VisitGetRentalReportsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRentedBooksByStudent operation middleware
func (sh *strictHandler) GetRentedBooksByStudent(w http.ResponseWriter, r *http.Request, params GetRentedBooksByStudentParams) {
	var request GetRentedBooksByStudentRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRentedBooksByStudent(ctx, request.(GetRentedBooksByStudentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRentedBooksByStudent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRentedBooksByStudentResponseObject); ok {
		if err := validResponse.VisitGetRentedBooksByStudentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReturnBooks operation middleware
func (sh *strictHandler) ReturnBooks(w http.ResponseWriter, r *http.Request) {
	var request ReturnBooksRequestObject

	var body ReturnBooksJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReturnBooks(ctx, request.(ReturnBooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReturnBooks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReturnBooksResponseObject); ok {
		if err := validResponse.VisitReturnBooksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAllStudents operation middleware
func (sh *strictHandler) ListAllStudents(w http.ResponseWriter, r *http.Request, params ListAllStudentsParams) {
	var request ListAllStudentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAllStudents(ctx, request.(ListAllStudentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAllStudents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAllStudentsResponseObject); ok {
		if err := validResponse.VisitListAllStudentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddStudent operation middleware
func (sh *strictHandler) AddStudent(w http.ResponseWriter, r *http.Request) {
	var request AddStudentRequestObject

	var body AddStudentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddStudent(ctx, request.(AddStudentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddStudent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddStudentResponseObject); ok {
		if err := validResponse.VisitAddStudentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStudentById operation middleware
func (sh *strictHandler) GetStudentById(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetStudentByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStudentById(ctx, request.(GetStudentByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStudentById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStudentByIdResponseObject); ok {
		if err := validResponse.VisitGetStudentByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbW/bOBL+KwTvgNsD5NhOnW7X35Lttggu3RZxi0PRDQJaHNtsJFJLUmm8hf/7YUi9",
	"WvRLEhfd9votFqkZDjnPzDND5TONVZopCdIaOv5MM6ZZCha0+5WIVNg3+Ah/cTCxFpkVStIxfcXuRJqn",
	"RObpFDRRMyIspIZYRTTYXMsjGlGBM//MQS9pRCVLgY69UBpREy8gZV7wjOWJpePjQURnSqfM0jEV0j45",
	"phFNvSI6Hg4GEU2FLH5F1C4z8BNhDpquVhFVs5mBTUv+vbtUcyMyMoWZ0lAsW8g5sQv8ZfLEmk1WeEVh",
	"M4JWlOseBNa9iqgGkylpwO37ubSgJUsmoG9B/6a10vg4VtKCtPgny7JExAwN6380aN1nCncszRLwMznQ",
	"8YnbMDCGzVHfqSS5hLsMYgucAEolKo5zrYHTVdOSf2qY0TH9R792jr4fNX2/Grfm9u6WiybGrdorQLnn",
	"8pYlgl/CnzkYe6b48iHGjNrGFEKJ9lKJE3sII8Ji2za8aaHkwJY0IHh4e9rC30mW24XS4i/gD/ay0WDY",
	"8rLcLkDa4jWnWBzGwTZIJkoTA8bgM7jLvLJKmzuhM6VuLkHaiWVFmNMqA22Fh9tUqZtrK6y3qkCnsVrI",
	"OXXQlBb4daxyvyuBsFM8UtOPEFt8BzUGNG2UsWZrYBWC4+MqruS54DTqTttkRmeREb3rzVWveJgqDok5",
	"wmU3R3oizZR2Ky7iXjEjY3aBvy4nZyy+Acn72c2876U4ZZU7rW8Ah25gdpOJGwuEzu5eVd4WFlQOR4FN",
	"qPxx/IEWCsvpV6uIXqi5kAXKu6vPmDHBw8kN6PCmN/W5WZGXcrXXeVyIqWZaMLn9UJrTdp7M61vQPId3",
	"xZLbFnJm4do7fMvd8HnPihRCPsfZ0lwrLzbs3NlCyTC4jM05SHvtLQlMsMqy5Hpa4mkf8L1hcyFdkDiX",
	"M9U1csHMtYQ72/Wf/y7ALkAjAdBAmAaSIjPwdIHdMpGwadLYg6lSCTCJSlFopuFWqNzsI7icu5dwz5n2",
	"5mCeyQCn2/lSSZd2MyWkSVlb3iAkzx1WV9xbfNxZZdPkrfQocMQYzS+hhEH7eK3Kan9xqnalnHZ+qPUx",
	"rdmydkJdsuQNhl8Xzry3o3orNgQbl5UEb1uxO/6vrbzE117pYy1eNd6N6uVcbTBkkqcp08t7p9eY6T2X",
	"51PxfeYCv8bItX8o2xGOQoc4aRx62/CZ0Mb+vimw7WlGwrbISNlHpYMjuyNuzDQv9vJBXKGwe3tmqift",
	"yEu4MIhzLexygqgs6YK6EYDEz6EAY4l/VBdiBfW7bu4ey8R/YOmliiIFrHFJgmFAwwKkEbdATt+ckxlS",
	"ByYxecwJI4lLqst/GYIOTNCdsLhZGgtpRISMk5wLOR+TP2SPVBmYsDZLxUEML0TIW5BW6aXXASlI60aL",
	"LSIa5sJY7V9jkq/PO2usAod9kCdWM2lYjG8ZnFakd3we3zhL3Fw8FyHnfyBFKLDouBy59BInzi7cBxrR",
	"W9DG79PwaHA0cJkiA8kyQcf0ydHg6ElxoO6Q+lWwnYdyySVYLeAWCEsSt5UGGftMJBY0mS6xJLGCJcSt",
	"CofOn1Onz2/FOXcEx9jXegJMxwtPraNWq+LDutLX7g9XjOI7xIJOyU9tVSmz8QIVwh2LLTl/7p/8m0Z1",
	"kUPfLgDPTM3Ib7egl3aBCAm3BMqfdZmTsrsLkHP03rJ5Uf0OBN9wkqrt7Df6MXvMbvZCVldrLYbjwWCP",
	"Yq82ZZ0IlwxrV2pd42K+05En9n7JOZCUu6G4WzFO8jgGY2Z5kiwRL84POUmEsXii01LyyG9GaBXVpvU3",
	"tgCcgOFuAd1qexXRk/1Ud/tBLmKWKdcBxBfCzt09zH5SmnuMSfiULEmsgVngfhTd3LI5gqeoVrH+yZQJ",
	"QhhDE2jCUJKPh0K6NlkRJevw1sHuKedF0agf3gFyZfPJ+vm+XQB5iUaRl8ya6TIiUt1CghafpqBFXMRj",
	"pcmLIzKJlbXkhbB/zUGzhEcky6eJMAvgaM3wl+OTo0Z0XBe+fwej8Ng2nbI6h1UHhMNHgLBRBdfxysV0",
	"xjlwYhreH+R6O/GzWdgCGC/aXxcqriJB+/V3lxcIM3STrgMSDUblOoZWuC1ySXOna4akRcCM1cPwWzb2",
	"vjpyTzlvwCoAylVE+4maC7fBYXw2OmMlIpGKxBqQWQiWGMcC/PYTVrbLumnWqXkEUH2DxDM5eMOM+YSs",
	"zHdHKOOpkPujqNWK2QtMg/stttoox4Lp8PjJ6OTpz896cPzLtDca8lGP/Tx82huNnj49ORmNBoPBgDY7",
	"nW6BDWC0TWtjta1rD9rfAPcDgLu+NNKrWqQFBtsYnoDt/eqJdce5JuWLbpxYRVImpGVCksSrsVhiNW0P",
	"Y3R4gO5y2c9uuPYBu+ToqEjmMJOiK39Smj8e6kVZQ8cfrprAr3GaFLArkd9udNchQOV2cwwobECAY8B1",
	"1zrSVseO+PciGmnbdww7MQD1HJQuBjOVV9TET/RAV18T86UOrNDU3LqtJ1Z0RDdXRo60lT0j8knYBSne",
	"aZacJlwN+YmX1ZS1cihUoKxX/tsg+6MYCUpoNs8fVJJcFLVHedAYcr6TGuQl2Mqs2nVLiPhubUloqlZq",
	"AYyug1+6GTvK/BdVF8EBxtf1VZlflfMhMLiupPt7Bww2aSzQRFyXDzNGwowlLn3st4JWr/GBi3Ax3gX9",
	"n96/f/++9+pV7/nzTQr5ep5u9UTpj47EnkGg2e1+VBDQvu8XK82/oxhQtldYkjgLy9RWtuR8668dG6Td",
	"3n+QlijpeJm7kPP9Dauwlqk6zO0Y8qvjufjm27pD+pjapr6P+bBPrTCkER34ab9snXbVvqShz35+ejJ6",
	"cjzc8tLx/py3ecX0xTsS97nK2di9MMTf3Bygf+H8pmw6tMR9400D79zlbYBtOfg6qHy69cl3Z4++fStS",
	"3nlYZoWxIjaNy4QuLX0J1tPRy2rCWvL++yaT3RByF1ubfMxvSaPFfABn+xtG9sIfvLVbuJ3NtdzM7go/",
	"AdcWNmfL5h3hFq5X3pNh9UJcTHlsjfODgZRtgmRZBl2fWWt6+x1dj3jTuhYvWyyiHT4jDI3Omx07yQPu",
	"7CeUt5L3oxePT6Trn7QVL14FfeAQDdQD5/4HZPVfmbYkZfoGOGGNj52+8Zz+iukbwjC82ZZZ21wSw23z",
	"o6MdF/CkiFGNO1BP0v31HuatUlio53SaJJN6/JvJ7V8vTFe79SVur01D+HcSodEZGx5Y+n21jZsrxPoW",
	"rWzLWOUa3f57ndCldE07Hhqz9zv6r3INXJKlQ90Eb5V32Mvg/5ub37WvKroUpOH3zUDf/yz4ane052CZ",
	"SNy3DX4j3TXQVOUW+U4GsZiJeGP75CXYQv3Z8pzv4uZvF0DOn5fnO6khWIatkq27rwArsu7YQRsb4fMP",
	"U58vWfS18RsGw0zlkj/OlUaD0ZeCvlTlCh+F+FrMYWtJVrnJdOk/+Qu5ffs6rv1B6Icr9AD/32Yhp8RY",
	"lBADNs9oRHOd0DFdWJuN+/0EhxbK2PGzwbMBXV2t/hcAAP//JXUfygk5AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
